## NumPy 2D array

Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.

In [4]:
import numpy as np
a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## NumPy 0s and 1s

Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1

In [5]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
for i in a:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

## NumPy Inclusive

Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

In [6]:
import numpy as np
a=np.arange(9,50,dtype=int)
for i in a:
    print(i,end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

## Identity Matrix

Create an integer identity matrix of size (5, 6).
Print the Numpy array.

In [7]:
import numpy as np
a=np.eye(5,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


## Cut the Rope

You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

Print the array element.

In [8]:
import numpy as np
a=np.linspace(0.56,4.44,8)
for i in a:
    print(f'{i:.2f}')

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


## Print Elements
Given a 2D integer array size (4, 5) with name input_?

Print elements of highlighted matrix

In [11]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a=input_[2,0:3]
for i in a:
    print(i,end=' ')
print('')
a=input_[1:4,3]
for i in a:
    print(i,end=' ')
print('')
a=input_[2:4,0:6]
for i in a:
    for j in i:
        print(j,end=' ')
print('')
a=input_[1:3,1:3]
for i in a:
    for j in i:
        print(j,end=' ')

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

## Non-Zero elements

#### Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?

Print the index of non-zero elements.

In [12]:
import numpy as np
ae=[1,2,0,0,4,0]
a=np.array(ae)
b=np.where(a>0)
for i in b:
    for j in i:
        print(j,end='')

014

## Multiples of 3

#### Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.

Note: Generate the following array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Print the index of elements.

In [13]:
import numpy as np
a=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
b=np.where(a%3==0)
for i in b:
    for j in i:
        print(j,)

1
4
7


## Odd elements

#### Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?

Note: Generate the following array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Print the Numpy array.

In [14]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[np.where(a%2!=0)]=-1
for i in a:
    print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

## Replace Max

#### Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?

Note: Generate the following array

array([11, 2, 13, 4, 15, 6, 27, 8, 19])

Print the Numpy array.

In [15]:
import numpy as np
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a[a.argmax()]=0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


## Negate Elements

#### Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

Note: Generate the following array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Print the Numpy array.

In [16]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[2:8]=a[2:8]*-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


## Height

#### Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). 

Print the age of those students whose height is above 155 cm.

Print the Numpy array.

In [17]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
b=height>155
c={}
c=age[b]
d=height[b]
n=len(c)
for i in range(0,n,1):
    print(c[i]," ",d[i])

15   156
19   180
20   162
21   157
22   158
23   179
16   182
18   183
20   159
15   160
17   172


## Sort by column

Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.